name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Trigger saat ada perubahan di branch utama
  schedule:
    - cron: "0 20 * * *"  # Jalankan setiap hari pukul 20:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: github-contribution-grid-snake.svg  # Simpan di branch 'main'

      - name: Commit and Push Snake Animation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "chore: update snake animation" || echo "No changes to commit"
          git push
